FROM raster-vision-tf:latest

RUN cat extras_requirements.json | jq  '.["tensorflow-cpu"][]' | xargs pip install

COPY scripts/rastervision /usr/local/bin/
COPY rastervision /opt/src/rastervision
COPY scripts/compile /opt/src/scripts/compile
RUN /opt/src/scripts/compile

CMD ["bash"]