FROM raster-vision-cuda-9.0:latest

RUN pip install numpy==1.14.5

# Install TF Object Detection API and Deeplab in /opt/tf-models
RUN mkdir -p /opt/tf-models/temp/ && \
    cd /opt/tf-models/temp/ && \
    git clone --single-branch -b AZ-v1.11-RV-v0.8.0 https://github.com/azavea/models.git && \
    mv models/research/object_detection/ ../object_detection && \
    mv models/research/deeplab/ ../deeplab && \
    mv models/research/slim/ ../slim && \
    cd .. && \
    rm -R temp && \
    protoc object_detection/protos/*.proto --python_out=. && \
    pip install cython==0.28.* && \
    pip install pycocotools==2.0.*

ENV PYTHONPATH=/opt/tf-models:/opt/tf-models/slim:$PYTHONPATH