#!/bin/bash
set -ex

apt-get update
apt-get install -y wget=1.* git=1:2.* \
    python-protobuf=2.* python3-tk=3.*

# Install protoc
wget -O /tmp/protoc3.zip https://github.com/google/protobuf/releases/download/v3.2.0/protoc-3.2.0-linux-x86_64.zip
unzip /tmp/protoc3.zip -d /tmp/protoc3
mv /tmp/protoc3/bin/* /usr/local/bin/
mv /tmp/protoc3/include/* /usr/local/include/
rm -R /tmp/protoc3
rm /tmp/protoc3.zip

# Install Python deps
pip install keras==2.1.* flake8==3.5.* awscli==1.15.* boto3==1.6.* \
    moto==1.3.* coverage==4.5.* yapf==0.22.* unify==0.4

# Install Rasterio
add-apt-repository ppa:ubuntugis/ppa
apt-gget update
apt-get install -y python-numpy=1:1.11.* gdal-bin=2.1.* \
    libgdal-dev=2.1.*
pip install rasterio==0.36.*

# Install TF Object Detection API in /opt/tf-models
mkdir -p /opt/tf-models/temp/
cd /opt/tf-models/temp/
git clone https://github.com/azavea/models.git
cd models
git checkout lf/fix-python3
git checkout f115b0551a05bb574d22f2e90825729867da4810
cd ..
mv models/research/object_detection/ ../object_detection
mv models/research/deeplab/ ../deeplab
mv models/research/slim/ ../slim
cd ..
rm -R temp
protoc object_detection/protos/*.proto --python_out=.
pip install cython==0.28.*
pip install pycocotools==2.0.*
