#!/bin/bash

apt-get update
apt-get install -y wget=1.17.1-1ubuntu1.4 git=1:2.7.4-0ubuntu1.3 \
    python-protobuf=2.6.1-1.3 python3-tk=3.5.1-1

# Install protoc
wget -O /tmp/protoc3.zip https://github.com/google/protobuf/releases/download/v3.2.0/protoc-3.2.0-linux-x86_64.zip
unzip /tmp/protoc3.zip -d /tmp/protoc3
mv /tmp/protoc3/bin/* /usr/local/bin/
mv /tmp/protoc3/include/* /usr/local/include/
rm -R /tmp/protoc3
rm /tmp/protoc3.zip

# Install Python deps
pip install keras==2.1.6 flake8==3.5.0 awscli==1.15.26 lxml==4.2.1 \
    shapely==1.6.4 boto3==1.6.0 pyproj==1.9.5.1 imageio==2.3.0 \
    scikit-learn==0.19.1 six==1.11.0 h5py==2.7.1 matplotlib==2.1.2 \
    pillow==5.0.0 click==6.7 npstreams==1.4.0

# Install Rasterio
add-apt-repository ppa:ubuntugis/ppa
apt-get update
apt-get install -y python-numpy=1:1.11.0-1ubuntu1 gdal-bin=2.1.3+dfsg-1~xenial2 \
    libgdal-dev=2.1.3+dfsg-1~xenial2
pip install rasterio==0.36.0

# Install TF Object Detection API in /opt/tf-models
mkdir -p /opt/tf-models/temp/
cd /opt/tf-models/temp/
git clone https://github.com/azavea/models.git
cd models
git checkout lf/fix-python3
git checkout eef6bb
cd ..
mv models/research/object_detection/ ../object_detection
mv models/research/slim/ ../slim
cd ..
rm -R temp
protoc object_detection/protos/*.proto --python_out=.
pip install cython==0.28.2
pip install pycocotools==2.0.0
