#!/bin/bash

set -e

if [[ -n "${RASTER_VISION_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
"Usage: $(basename "$0") [TEST_NAMES]
Run integration tests.
"
}

if [ "${1:-}" = "--help" ]; then
    usage
else
    if ! [ -x "$(command -v coverage)" ]; then
	python -m integration_tests ${@:1}
    else
	coverage run --append --source=rastervision --omit=rastervision/protos -a -m integration_tests ${@:1}
    fi
fi
