#!/bin/bash

# Script to run a command on a specific branch of RV. Used for running commands
# in AWS Batch jobs.

set -ex

BRANCH=$1
COMMAND="${@:2}"

git clone -b $BRANCH https://github.com/azavea/raster-vision.git /tmp/raster-vision
cp -R /tmp/raster-vision/src/* /opt/src/
/opt/src/scripts/compile
$COMMAND
