#!/bin/bash

# Script to run a command on a specific branch of RV. Used for running commands
# in AWS Batch jobs.

set -ex

REPO=$1
BRANCH=$2
COMMAND="${@:3}"

git clone -b $BRANCH $REPO /tmp/raster-vision
cp -R /tmp/raster-vision/src/* /opt/src/
/opt/src/scripts/compile
$COMMAND
