#!/bin/bash

set -e

if [[ -n "${RASTER_VISION_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
"Usage: $(basename "$0")
Run all unit tests.
"
}

if [ "${1:-}" = "--help" ]; then
    usage
else
    if ! [ -x "$(command -v coverage)" ]; then
	python -m unittest discover tests
    else
	coverage run --append --source=rastervision --omit=rastervision/protos -m unittest discover tests
    fi
fi
