#!/bin/bash

FAMILY=quay.io/azavea
CUDA_VERSION="10.0"
BASE_STRING=$(cat Dockerfile.base | md5sum | cut -f1 -d' ')
BASE_IMAGE=${FAMILY}/raster-vision:base-${BASE_STRING}-cuda${CUDA_VERSION}
PYBASE_STRING=$(cat Dockerfile.base Dockerfile.pybase ./docs/requirements.txt ./requirements-dev.txt ./rastervision*/requirements.txt | md5sum | cut -f1 -d' ')
PYBASE_IMAGE=${FAMILY}/raster-vision:pybase-${PYBASE_STRING}


set -e

if [[ -n "${RASTER_VISION_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
         "Usage: $(basename "$0")
Build Docker images.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
        exit
    fi

    if ! docker pull ${BASE_IMAGE} && ! docker images | grep ${BASE_STRING}; then
	docker build --build-arg CUDA_VERSION=${CUDA_VERSION} -t ${BASE_IMAGE} -f Dockerfile.base .
    fi
    if ! docker pull ${PYBASE_IMAGE} && ! docker images | grep ${PYBASE_STRING}; then
	docker build --build-arg BASE_IMAGE=${BASE_IMAGE} -t ${PYBASE_IMAGE} -f Dockerfile.pybase .
    fi
    docker build --build-arg PYBASE_IMAGE=${PYBASE_IMAGE} -t raster-vision-pytorch -f Dockerfile .
fi
