#!/bin/bash

set -e

if [[ -n "${RASTER_VISION_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
         "Usage: $(basename "$0") [--tf|--pytorch]
Build Docker images.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
        exit
    fi

    if [ $# -eq 0 -o "${1:-}" = "--tf" ]
    then
        docker build --build-arg CUDA_VERSION="9.0" -t raster-vision-cuda-9.0 -f Dockerfile .
        docker build -t raster-vision-tf -f Dockerfile-tf .
        docker build -t raster-vision-tf-cpu -f Dockerfile-tf-cpu .
        docker build -t raster-vision-tf-gpu -f Dockerfile-tf-gpu .
    fi
    if [ $# -eq 0 -o "${1:-}" = "--pytorch" ]
    then
        docker build --build-arg CUDA_VERSION="10.0" -t raster-vision-cuda-10.0 -f Dockerfile .
        docker build -t raster-vision-pytorch -f Dockerfile-pytorch .
    fi
fi
