#!/bin/bash

set -e

if [[ -n "${RASTER_VISION_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
         "Usage: $(basename "$0")
Build Docker images.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
        exit
    fi

    PLATFORM="amd64"
    if [ "${1:-}" = "--arm64" ]
    then
        PLATFORM="arm64"
    fi

    DOCKER_BUILDKIT=1 docker build \
        --platform linux/${PLATFORM} --build-arg CUDA_VERSION="11.3.1" \
        -t raster-vision-pytorch-${PLATFORM} -f Dockerfile .
fi
