#!/bin/bash

set -e

if [[ -n "${RASTER_VISION_DEBUG}" ]]; then
    set -x
fi

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
SCRIPTS_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
PROJECT_ROOT="$( cd -P "$( dirname "$SCRIPTS_DIR" )" && pwd )"

function usage() {
    echo -n \
         "Usage: $(basename "$0") (--local|--remote)
Run the jupyter notebook in a raster-vision docker image locally
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ -n ${RASTER_VISION_NOTEBOOK_DIR} ]; then
        docker run --rm -it \
               -e "AWS_PROFILE=$AWS_PROFILE" \
               -v "$HOME/.aws":/root/.aws:ro \
               -v "$PROJECT_ROOT":/opt/src \
               -v ${RASTER_VISION_DATA_DIR}:/opt/data \
               -v ${RASTER_VISION_NOTEBOOK_DIR}:/opt/notebooks \
               -p 8888:8888 \
               raster-vision-cpu \
               /run_jupyter.sh \
               --ip 0.0.0.0 \
               --port 8888 \
               --no-browser \
               --allow-root \
               --notebook-dir=/opt/notebooks;
    else
        docker run --rm -it \
               -e "AWS_PROFILE=$AWS_PROFILE" \
               -v "$HOME/.aws":/root/.aws:ro \
               -v "$PROJECT_ROOT":/opt/src \
               -v ${RASTER_VISION_DATA_DIR}:/opt/data \
               -p 8888:8888 \
               raster-vision-cpu \
               /run_jupyter.sh \
               --ip 0.0.0.0 \
               --port 8888 \
               --no-browser \
               --allow-root \
               --notebook-dir=/opt/src;
    fi
fi
