#!/bin/bash

set -e

function usage() {
    echo -n \
         "Usage: $(basename "$0") <python module + args>
Run a Python module using VS code debugger.

Example:
./scripts/debug some.python.module
"
}

python -m ptvsd --host 0.0.0.0 --port 3000 --wait -m ${@:1}
