#!/bin/bash

source .travis/env

if [ "$IMAGE_TYPE" = "tf" ]; then
    docker run -w $(pwd) -v $(pwd):$(pwd) --rm ${PYTORCH_IMAGE} coverage xml
    docker run -e CODECOV_TOKEN=$CODECOV_TOKEN -v $(pwd):$(pwd) --rm ${PYTORCH_IMAGE} codecov --root=$(pwd) --commit=$TRAVIS_COMMIT
fi
