#!/bin/bash
set -e

if [ "$QUAY_USERNAME" != "" -a "$QUAY_PASSWORD" != "" ]; then
    if [ -z "${TRAVIS_TAG}" ]; then
        if [ "$TRAVIS_BRANCH" == "develop" ]; then
            echo "INFO: Push to develop branch, publishing commit and latest tags";
            .travis/build "BUILD_ALL" && \
                .travis/publish "$TRAVIS_COMMIT" "TRUE";
        else
            echo "INFO: non-tag branch is not 'develop', skipping publish";
        fi
    else
        echo "INFO: Push to tag, publishing tag name.";
        .travis/build "BUILD_ALL" && \
            .travis/publish "$TRAVIS_TAG" "FALSE";
    fi
else
    echo "Error: QUAY_USERNAME and/or QUAY_PASSWORD are not defined."
    exit 1;
fi
