#!/bin/bash
set -e

if [ "$QUAY_USERNAME" != "" -a "$QUAY_PASSWORD" != "" ]; then
    if [ -z "${TRAVIS_TAG}" ]; then
        if [ "$TRAVIS_BRANCH" == "develop" ]; then
            echo "INFO: Push to develop branch, publishing commit and latest tags";
            # Only use the first 7 characters of the commit hash
            COMMIT=${TRAVIS_COMMIT:0:7}
            .travis/build "BUILD_ALL" && \
                .travis/publish "$COMMIT" "TRUE";
        elif [[ $TRAVIS_BRANCH =~ ^[0-9]+(\.[0-9]+)*$ ]]; then
            echo "INFO: Push to release brach, publishing branch name.";
            .travis/build "BUILD_ALL" && \
                .travis/publish "$TRAVIS_BRANCH" "FALSE";
        fi
    else
        echo "INFO: Push to tag, publishing tag name.";
        .travis/build "BUILD_ALL" && \
            .travis/publish "$TRAVIS_TAG" "FALSE";
    fi
else
    echo "Error: QUAY_USERNAME and/or QUAY_PASSWORD are not defined."
    exit 1;
fi
