#!/bin/bash
set -e

source .travis/env

TAG_SUFFIX=${1}
IS_LATEST=${2}

docker login -u="$QUAY_USERNAME" -p="$QUAY_PASSWORD" quay.io

function tag_and_push() {
    if [ "$IMAGE_TYPE" = "pytorch" ]; then
        docker tag ${PYTORCH_IMAGE} "${PYTORCH_TAG}-${1}";
        docker push "${PYTORCH_TAG}-${1}";
    fi
}

tag_and_push ${TAG_SUFFIX}

if [ "$IS_LATEST" == "TRUE" ]; then
    tag_and_push "latest"
fi
