#!/bin/bash

set -x

docker run -v $(pwd):$(pwd) --rm raster-vision-cpu rm -f $(pwd)/src/.coverage

docker run --rm raster-vision-cpu /opt/src/scripts/style_tests && \
docker run -v $(pwd):$(pwd) --rm raster-vision-cpu $(pwd)/src/scripts/compile && \
docker run -v $(pwd):$(pwd) --rm raster-vision-cpu $(pwd)/src/scripts/unit_tests && \
docker run -v $(pwd):$(pwd) --rm raster-vision-cpu $(pwd)/src/scripts/integration_tests
