#!/bin/bash

docker run -v $(pwd):$(pwd) --rm -it raster-vision-cpu rm -f $(pwd)/src/.coverage $(pwd)/src/coverage.xml
docker run --rm raster-vision-cpu -it /opt/src/scripts/style_tests && \
docker run -w $(pwd)/src -v $(pwd):$(pwd) --rm -it raster-vision-cpu $(pwd)/src/scripts/compile && \
docker run -w $(pwd)/src -v $(pwd):$(pwd) --rm -it raster-vision-cpu $(pwd)/src/scripts/unit_tests && \
docker run -v $(pwd):$(pwd) --rm -it raster-vision-cpu $(pwd)/src/scripts/integration_tests
