# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rv2/protos/label_item.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rv2/protos/label_item.proto',
  package='rv.protos',
  syntax='proto2',
  serialized_pb=_b('\n\x1brv2/protos/label_item.proto\x12\trv.protos\"%\n\tLabelItem\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0c\n\x04name\x18\x02 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LABELITEM = _descriptor.Descriptor(
  name='LabelItem',
  full_name='rv.protos.LabelItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='rv.protos.LabelItem.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='rv.protos.LabelItem.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=79,
)

DESCRIPTOR.message_types_by_name['LabelItem'] = _LABELITEM

LabelItem = _reflection.GeneratedProtocolMessageType('LabelItem', (_message.Message,), dict(
  DESCRIPTOR = _LABELITEM,
  __module__ = 'rv2.protos.label_item_pb2'
  # @@protoc_insertion_point(class_scope:rv.protos.LabelItem)
  ))
_sym_db.RegisterMessage(LabelItem)


# @@protoc_insertion_point(module_scope)
