# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rv2/protos/machine_learning.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rv2/protos/machine_learning.proto',
  package='rv.protos',
  syntax='proto2',
  serialized_pb=_b('\n!rv2/protos/machine_learning.proto\x12\trv.protos\"\x80\x02\n\x0fMachineLearning\x12\x31\n\x06method\x18\x01 \x02(\x0e\x32!.rv.protos.MachineLearning.Method\x12\x33\n\x07\x62\x61\x63kend\x18\x02 \x02(\x0e\x32\".rv.protos.MachineLearning.Backend\"]\n\x06Method\x12\x14\n\x10OBJECT_DETECTION\x10\x01\x12\x12\n\x0e\x43LASSIFICATION\x10\x02\x12\x0e\n\nREGRESSION\x10\x03\x12\x19\n\x15SEMANTIC_SEGMENTATION\x10\x04\"&\n\x07\x42\x61\x63kend\x12\x1b\n\x17TF_OBJECT_DETECTION_API\x10\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_MACHINELEARNING_METHOD = _descriptor.EnumDescriptor(
  name='Method',
  full_name='rv.protos.MachineLearning.Method',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OBJECT_DETECTION', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLASSIFICATION', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REGRESSION', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SEMANTIC_SEGMENTATION', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=172,
  serialized_end=265,
)
_sym_db.RegisterEnumDescriptor(_MACHINELEARNING_METHOD)

_MACHINELEARNING_BACKEND = _descriptor.EnumDescriptor(
  name='Backend',
  full_name='rv.protos.MachineLearning.Backend',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TF_OBJECT_DETECTION_API', index=0, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=267,
  serialized_end=305,
)
_sym_db.RegisterEnumDescriptor(_MACHINELEARNING_BACKEND)


_MACHINELEARNING = _descriptor.Descriptor(
  name='MachineLearning',
  full_name='rv.protos.MachineLearning',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='method', full_name='rv.protos.MachineLearning.method', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='backend', full_name='rv.protos.MachineLearning.backend', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MACHINELEARNING_METHOD,
    _MACHINELEARNING_BACKEND,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=305,
)

_MACHINELEARNING.fields_by_name['method'].enum_type = _MACHINELEARNING_METHOD
_MACHINELEARNING.fields_by_name['backend'].enum_type = _MACHINELEARNING_BACKEND
_MACHINELEARNING_METHOD.containing_type = _MACHINELEARNING
_MACHINELEARNING_BACKEND.containing_type = _MACHINELEARNING
DESCRIPTOR.message_types_by_name['MachineLearning'] = _MACHINELEARNING

MachineLearning = _reflection.GeneratedProtocolMessageType('MachineLearning', (_message.Message,), dict(
  DESCRIPTOR = _MACHINELEARNING,
  __module__ = 'rv2.protos.machine_learning_pb2'
  # @@protoc_insertion_point(class_scope:rv.protos.MachineLearning)
  ))
_sym_db.RegisterMessage(MachineLearning)


# @@protoc_insertion_point(module_scope)
