# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rv2/protos/predict.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from rv2.protos import machine_learning_pb2 as rv2_dot_protos_dot_machine__learning__pb2
from rv2.protos import project_pb2 as rv2_dot_protos_dot_project__pb2
from rv2.protos import label_item_pb2 as rv2_dot_protos_dot_label__item__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rv2/protos/predict.proto',
  package='rv.protos',
  syntax='proto2',
  serialized_pb=_b('\n\x18rv2/protos/predict.proto\x12\trv.protos\x1a!rv2/protos/machine_learning.proto\x1a\x18rv2/protos/project.proto\x1a\x1brv2/protos/label_item.proto\"\xb6\x03\n\x07Predict\x12\x34\n\x10machine_learning\x18\x01 \x02(\x0b\x32\x1a.rv.protos.MachineLearning\x12)\n\x0blabel_items\x18\x03 \x03(\x0b\x32\x14.rv.protos.LabelItem\x12$\n\x08projects\x18\x04 \x03(\x0b\x32\x12.rv.protos.Project\x12+\n\x07options\x18\x05 \x02(\x0b\x32\x1a.rv.protos.Predict.Options\x1aN\n\x16ObjectDetectionOptions\x12\x19\n\x0cmerge_thresh\x18\x01 \x01(\x02:\x03\x30.5\x12\x19\n\x0cscore_thresh\x18\x02 \x01(\x02:\x03\x30.5\x1a\xa6\x01\n\x07Options\x12\x11\n\tmodel_uri\x18\x01 \x02(\t\x12\x11\n\tchip_size\x18\x03 \x02(\x05\x12\x13\n\x05\x64\x65\x62ug\x18\x04 \x01(\x08:\x04true\x12M\n\x18object_detection_options\x18\x05 \x01(\x0b\x32).rv.protos.Predict.ObjectDetectionOptionsH\x00\x42\x11\n\x0fml_options_type')
  ,
  dependencies=[rv2_dot_protos_dot_machine__learning__pb2.DESCRIPTOR,rv2_dot_protos_dot_project__pb2.DESCRIPTOR,rv2_dot_protos_dot_label__item__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PREDICT_OBJECTDETECTIONOPTIONS = _descriptor.Descriptor(
  name='ObjectDetectionOptions',
  full_name='rv.protos.Predict.ObjectDetectionOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='merge_thresh', full_name='rv.protos.Predict.ObjectDetectionOptions.merge_thresh', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='score_thresh', full_name='rv.protos.Predict.ObjectDetectionOptions.score_thresh', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=321,
  serialized_end=399,
)

_PREDICT_OPTIONS = _descriptor.Descriptor(
  name='Options',
  full_name='rv.protos.Predict.Options',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_uri', full_name='rv.protos.Predict.Options.model_uri', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chip_size', full_name='rv.protos.Predict.Options.chip_size', index=1,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='debug', full_name='rv.protos.Predict.Options.debug', index=2,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='object_detection_options', full_name='rv.protos.Predict.Options.object_detection_options', index=3,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='ml_options_type', full_name='rv.protos.Predict.Options.ml_options_type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=402,
  serialized_end=568,
)

_PREDICT = _descriptor.Descriptor(
  name='Predict',
  full_name='rv.protos.Predict',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='machine_learning', full_name='rv.protos.Predict.machine_learning', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='label_items', full_name='rv.protos.Predict.label_items', index=1,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='projects', full_name='rv.protos.Predict.projects', index=2,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='options', full_name='rv.protos.Predict.options', index=3,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PREDICT_OBJECTDETECTIONOPTIONS, _PREDICT_OPTIONS, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=568,
)

_PREDICT_OBJECTDETECTIONOPTIONS.containing_type = _PREDICT
_PREDICT_OPTIONS.fields_by_name['object_detection_options'].message_type = _PREDICT_OBJECTDETECTIONOPTIONS
_PREDICT_OPTIONS.containing_type = _PREDICT
_PREDICT_OPTIONS.oneofs_by_name['ml_options_type'].fields.append(
  _PREDICT_OPTIONS.fields_by_name['object_detection_options'])
_PREDICT_OPTIONS.fields_by_name['object_detection_options'].containing_oneof = _PREDICT_OPTIONS.oneofs_by_name['ml_options_type']
_PREDICT.fields_by_name['machine_learning'].message_type = rv2_dot_protos_dot_machine__learning__pb2._MACHINELEARNING
_PREDICT.fields_by_name['label_items'].message_type = rv2_dot_protos_dot_label__item__pb2._LABELITEM
_PREDICT.fields_by_name['projects'].message_type = rv2_dot_protos_dot_project__pb2._PROJECT
_PREDICT.fields_by_name['options'].message_type = _PREDICT_OPTIONS
DESCRIPTOR.message_types_by_name['Predict'] = _PREDICT

Predict = _reflection.GeneratedProtocolMessageType('Predict', (_message.Message,), dict(

  ObjectDetectionOptions = _reflection.GeneratedProtocolMessageType('ObjectDetectionOptions', (_message.Message,), dict(
    DESCRIPTOR = _PREDICT_OBJECTDETECTIONOPTIONS,
    __module__ = 'rv2.protos.predict_pb2'
    # @@protoc_insertion_point(class_scope:rv.protos.Predict.ObjectDetectionOptions)
    ))
  ,

  Options = _reflection.GeneratedProtocolMessageType('Options', (_message.Message,), dict(
    DESCRIPTOR = _PREDICT_OPTIONS,
    __module__ = 'rv2.protos.predict_pb2'
    # @@protoc_insertion_point(class_scope:rv.protos.Predict.Options)
    ))
  ,
  DESCRIPTOR = _PREDICT,
  __module__ = 'rv2.protos.predict_pb2'
  # @@protoc_insertion_point(class_scope:rv.protos.Predict)
  ))
_sym_db.RegisterMessage(Predict)
_sym_db.RegisterMessage(Predict.ObjectDetectionOptions)
_sym_db.RegisterMessage(Predict.Options)


# @@protoc_insertion_point(module_scope)
