# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rv2/protos/raster_transformer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rv2/protos/raster_transformer.proto',
  package='rv.protos',
  syntax='proto2',
  serialized_pb=_b('\n#rv2/protos/raster_transformer.proto\x12\trv.protos\"*\n\x11RasterTransformer\x12\x15\n\rchannel_order\x18\x01 \x03(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RASTERTRANSFORMER = _descriptor.Descriptor(
  name='RasterTransformer',
  full_name='rv.protos.RasterTransformer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel_order', full_name='rv.protos.RasterTransformer.channel_order', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=92,
)

DESCRIPTOR.message_types_by_name['RasterTransformer'] = _RASTERTRANSFORMER

RasterTransformer = _reflection.GeneratedProtocolMessageType('RasterTransformer', (_message.Message,), dict(
  DESCRIPTOR = _RASTERTRANSFORMER,
  __module__ = 'rv2.protos.raster_transformer_pb2'
  # @@protoc_insertion_point(class_scope:rv.protos.RasterTransformer)
  ))
_sym_db.RegisterMessage(RasterTransformer)


# @@protoc_insertion_point(module_scope)
