# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rv2/protos/train.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from rv2.protos import machine_learning_pb2 as rv2_dot_protos_dot_machine__learning__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rv2/protos/train.proto',
  package='rv.protos',
  syntax='proto2',
  serialized_pb=_b('\n\x16rv2/protos/train.proto\x12\trv.protos\x1a!rv2/protos/machine_learning.proto\"\xee\x01\n\x05Train\x12\x34\n\x10machine_learning\x18\x01 \x02(\x0b\x32\x1a.rv.protos.MachineLearning\x12)\n\x07options\x18\x02 \x02(\x0b\x32\x18.rv.protos.Train.Options\x1a\x83\x01\n\x07Options\x12\x12\n\nconfig_uri\x18\x01 \x02(\t\x12\x16\n\x0etrain_data_uri\x18\x02 \x02(\t\x12\x12\n\noutput_uri\x18\x03 \x02(\t\x12\x1c\n\x14model_checkpoint_uri\x18\x04 \x01(\t\x12\x1a\n\rsync_interval\x18\x05 \x01(\x05:\x03\x36\x30\x30')
  ,
  dependencies=[rv2_dot_protos_dot_machine__learning__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TRAIN_OPTIONS = _descriptor.Descriptor(
  name='Options',
  full_name='rv.protos.Train.Options',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='config_uri', full_name='rv.protos.Train.Options.config_uri', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='train_data_uri', full_name='rv.protos.Train.Options.train_data_uri', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output_uri', full_name='rv.protos.Train.Options.output_uri', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='model_checkpoint_uri', full_name='rv.protos.Train.Options.model_checkpoint_uri', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sync_interval', full_name='rv.protos.Train.Options.sync_interval', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=600,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=311,
)

_TRAIN = _descriptor.Descriptor(
  name='Train',
  full_name='rv.protos.Train',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='machine_learning', full_name='rv.protos.Train.machine_learning', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='options', full_name='rv.protos.Train.options', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_TRAIN_OPTIONS, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=311,
)

_TRAIN_OPTIONS.containing_type = _TRAIN
_TRAIN.fields_by_name['machine_learning'].message_type = rv2_dot_protos_dot_machine__learning__pb2._MACHINELEARNING
_TRAIN.fields_by_name['options'].message_type = _TRAIN_OPTIONS
DESCRIPTOR.message_types_by_name['Train'] = _TRAIN

Train = _reflection.GeneratedProtocolMessageType('Train', (_message.Message,), dict(

  Options = _reflection.GeneratedProtocolMessageType('Options', (_message.Message,), dict(
    DESCRIPTOR = _TRAIN_OPTIONS,
    __module__ = 'rv2.protos.train_pb2'
    # @@protoc_insertion_point(class_scope:rv.protos.Train.Options)
    ))
  ,
  DESCRIPTOR = _TRAIN,
  __module__ = 'rv2.protos.train_pb2'
  # @@protoc_insertion_point(class_scope:rv.protos.Train)
  ))
_sym_db.RegisterMessage(Train)
_sym_db.RegisterMessage(Train.Options)


# @@protoc_insertion_point(module_scope)
