#!/bin/bash
set -e

if [ "$IMAGE_TYPE" = "pytorch" ]; then
    PYTORCH_IMAGE=raster-vision-pytorch

    docker build \
        --build-arg CUDA_VERSION="10.2" \
        -t "${PYTORCH_IMAGE}" \
        -f Dockerfile \
        .

    docker run \
        -w "$(pwd)" \
        -v "$(pwd)":"$(pwd)" \
        --rm \
        "${PYTORCH_IMAGE}" \
        rm -f "$(pwd)"/.coverage "$(pwd)"/coverage.xml
    docker run \
        --rm \
        "${PYTORCH_IMAGE}" \
        /opt/src/scripts/style_tests
    docker run \
        --rm \
        "${PYTORCH_IMAGE}" \
        /opt/src/scripts/unit_tests
    docker run \
        --rm \
        "${PYTORCH_IMAGE}" \
        /opt/src/scripts/integration_tests

    docker run \
        -w "$(pwd)" \
        -v "$(pwd):$(pwd)" \
        --rm \
        "${PYTORCH_IMAGE}" \
        coverage xml
    docker run \
        -v "$(pwd)":"$(pwd)" \
        --rm \
        ${PYTORCH_IMAGE} \
        codecov --root="$(pwd)" --commit="${GITHUB_SHA}"
fi
