#!/bin/bash

set -e

if [[ -n ${RASTER_VISION_DEBUG} ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Publish container images to Quay.io.
"
}

docker login -u="${QUAY_USER}" -p="${QUAY_PASSWORD}" quay.io

if [ "${IMAGE_TYPE}" = "pytorch" ]; then
    docker tag "raster-vision-pytorch" \
        "quay.io/azavea/raster-vision:pytorch-${IMAGE_VERSION}"
    docker push "quay.io/azavea/raster-vision:pytorch-${IMAGE_VERSION}"
fi
