#!/bin/bash

set -e

if [[ -n "${RASTER_VISION_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
         "Usage: $(basename "$0")
Publish Docker containers to ECR.
"
}

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
SCRIPTS_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
PROJECT_ROOT="$( cd -P "$( dirname "$SCRIPTS_DIR" )" && pwd )"

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        $PROJECT_ROOT/scripts/update
        `aws ecr get-login --region us-east-1 --no-include-email`
        docker tag raster-vision-gpu:latest 279682201306.dkr.ecr.us-east-1.amazonaws.com/raster-vision-gpu:latest
        docker push 279682201306.dkr.ecr.us-east-1.amazonaws.com/raster-vision-gpu:latest

        docker tag raster-vision-cpu:latest 279682201306.dkr.ecr.us-east-1.amazonaws.com/raster-vision-cpu:latest
        docker push 279682201306.dkr.ecr.us-east-1.amazonaws.com/raster-vision-cpu:latest
    fi
fi
