#!/bin/bash

set -e

pushd /dev
rm random urandom
ln -s zero random
ln -s zero urandom
popd

if [[ -n "${RASTER_VISION_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
"Usage: $(basename "$0") [TEST_NAMES]
Run integration tests.
"
}

if [ "${1:-}" = "--help" ]; then
    usage
else
    python -m integration_tests ${@:1}
fi
