#!/bin/bash

set -e

if [[ -n "${RASTER_VISION_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
"Usage: $(basename "$0") [TEST_NAMES]
Run integration tests.
"
}

if [ "${1:-}" = "--help" ]; then
    usage
else
    # setting these env vars is a kludge to allow this to run in CI where there is no
    # profile set. in the future we should have a mechanism for default values for
    # everett fields.
    AWS_BATCH_CPU_JOB_DEF="" AWS_BATCH_CPU_JOB_QUEUE="" AWS_BATCH_GPU_JOB_DEF="" AWS_BATCH_GPU_JOB_QUEUE="" AWS_BATCH_ATTEMPTS="" AWS_S3_REQUESTER_PAYS="False" \
        python -m integration_tests2 ${@:1}
fi
