#!/bin/bash

set -e

if [[ -n "${RASTER_VISION_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
         "Usage: $(basename "$0")
Setup AWS Batch with a compute environment, job queue and job definition. This
should only be done once per AWS account.
"
}

PROJECT_ROOT="$(dirname "$(dirname "$(readlink -f "${0}")")")"
BATCH_CONFIG=$PROJECT_ROOT/deployment/batch

echo aws batch create-compute-environment --cli-input-json file://$BATCH_CONFIG/compute_environment.json
echo aws batch create-job-queue --cli-input-json file://$BATCH_CONFIG/job_queue.json
echo aws batch register-job-definition --cli-input-json file://$BATCH_CONFIG/job_def.json
