#!/bin/bash

set -e

if [[ -n "${RASTER_VISION_DEBUG}" ]]; then
    set -x
fi

PROJECT_ROOT="$(dirname "$(dirname "$(readlink -f "${0}")")")"
SRC="$PROJECT_ROOT/src"

docker run --rm -it \
    -v "$SRC":/opt/src \
    raster-vision-cpu python -m unittest

docker run --rm -it \
    -v "$SRC":/opt/src \
    raster-vision-cpu flake8 .
