#!/bin/bash

set -e

if [[ -n "${RASTER_VISION_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
"Usage: $(basename "$0")
Run all unit tests.
"
}

if [ "${1:-}" = "--help" ]; then
    usage
else
    # If the command `coverage` exists (provided by coverage.py), then
    # use it to run the unit tests.  Otherwise, use the normal Python
    # executable.
    if ! [ -x "$(command -v coverage)" ]; then
	python -m unittest discover tests
    else
	coverage run -m unittest discover tests
    fi
fi
