#!/bin/bash

export S3_BUCKET="${s3_bucket}"
echo "export S3_BUCKET=\"$S3_BUCKET\"" >> /etc/environment

cd /home/ec2-user

# Install command line tools
sudo yum install -y aws-cli git unzip

# Install nvidia-docker and nvidia-docker-plugin
wget -P /tmp https://github.com/NVIDIA/nvidia-docker/releases/download/v1.0.1/nvidia-docker_1.0.1_amd64.tar.xz
sudo tar --strip-components=1 -C /usr/bin -xvf /tmp/nvidia-docker*.tar.xz && rm /tmp/nvidia-docker*.tar.xz

# Run nvidia-docker-plugin
sudo -b nohup nvidia-docker-plugin > /tmp/nvidia-docker.log

# Setup data directory
sudo mkdir /home/ec2-user/data

# Download source repo
sudo -H -u ec2-user bash -c "yes | git clone https://github.com/azavea/raster-vision.git"

# Get docker container
`aws ecr get-login --region us-east-1`
docker pull 279682201306.dkr.ecr.us-east-1.amazonaws.com/raster-vision-gpu:latest
