# Based on https://github.com/fchollet/keras/blob/2b51317be82d4420169d2cc79dc4443028417911/docker/Dockerfile
FROM otid-model-training-base

USER keras

# Python
ARG tensorflow_version=0.10.0-cp35-cp35m
ARG architecture=cpu

RUN pip install https://storage.googleapis.com/tensorflow/linux/${architecture}/tensorflow-${tensorflow_version}-linux_x86_64.whl && \
    pip install git+git://github.com/fchollet/keras.git@38719480 &&\
    pip install git+git://github.com/jakebian/quiver.git

WORKDIR /opt/model_training

COPY . /opt/model_training

# Ensure that the keras user will have permission to write model
# outputs into /opt/model_training.
USER root
RUN chown -R keras:root /opt/model_training/output

# TODO move this to base
RUN conda install matplotlib
RUN conda install pillow

CMD ["python", "mnist_cnn.py"]
