# Based on https://github.com/fchollet/keras/blob/7c6463da6f972ffaa466b0f55d06b760a98caf8e/docker/Dockerfile
FROM keras-semantic-segmentation-base

USER keras

# Python
ARG tensorflow_version=0.10.0-cp35-cp35m
ARG architecture=cpu

RUN pip install https://storage.googleapis.com/tensorflow/linux/${architecture}/tensorflow-${tensorflow_version}-linux_x86_64.whl && \
    pip install git+git://github.com/fchollet/keras.git@7c6463da6f972ffaa466b0f55d06b760a98caf8e

WORKDIR /opt/src

COPY . /opt/src

# Ensure that the keras user will have permission to write model into /opt/data
USER root
RUN mkdir /opt/data
RUN chown -R keras:root /opt/data

CMD ["bash"]
