# Based on https://github.com/fchollet/keras/blob/2b51317be82d4420169d2cc79dc4443028417911/docker/Dockerfile
FROM nvidia/cuda:8.0-cudnn5-devel-ubuntu14.04

ENV CONDA_DIR /opt/conda
ENV PATH $CONDA_DIR/bin:$PATH

RUN mkdir -p $CONDA_DIR && \
    echo export PATH=$CONDA_DIR/bin:'$PATH' > /etc/profile.d/conda.sh && \
    apt-get update && \
    apt-get install -y wget git libhdf5-dev g++ graphviz libav-tools unzip p7zip-full && \
    wget --quiet https://repo.continuum.io/miniconda/Miniconda3-3.9.1-Linux-x86_64.sh && \
    echo "6c6b44acdd0bc4229377ee10d52c8ac6160c336d9cdd669db7371aa9344e1ac3 *Miniconda3-3.9.1-Linux-x86_64.sh" | sha256sum -c - && \
    /bin/bash /Miniconda3-3.9.1-Linux-x86_64.sh -f -b -p $CONDA_DIR && \
    rm Miniconda3-3.9.1-Linux-x86_64.sh

RUN apt-get install -y python-protobuf

ENV NB_USER keras
ENV NB_UID 1000

RUN useradd -m -s /bin/bash -N -u $NB_UID $NB_USER && \
    mkdir -p $CONDA_DIR && \
    chown keras $CONDA_DIR -R && \
    mkdir -p /src && \
    chown keras /src

ENV PYTHONPATH=/src/:$PYTHONPATH

ENV KERAS_BACKEND tensorflow

USER keras

# Python
ARG python_version=3.5.1

RUN conda install -y python=${python_version} scikit-learn six h5py \
        matplotlib pillow rasterio scikit-image opencv && \
    conda install -c conda-forge rtree && \
    conda clean -yt

RUN pip install flake8 awscli spectral lxml shapely pandas boto3==1.6.0 \
    pyproj imageio npstreams==1.4.0

# Ensure that the keras user will have permission to write model into /opt/data
USER root
RUN mkdir /opt/data
RUN chown -R keras:root /opt/data

# Needed for click to work
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

# install protoc
RUN wget -O /tmp/protoc3.zip https://github.com/google/protobuf/releases/download/v3.2.0/protoc-3.2.0-linux-x86_64.zip
RUN unzip /tmp/protoc3.zip -d /tmp/protoc3
RUN mv /tmp/protoc3/bin/* /usr/local/bin/
RUN mv /tmp/protoc3/include/* /usr/local/include/
RUN rm -R /tmp/protoc3
RUN rm /tmp/protoc3.zip
