FROM tensorflow/tensorflow:1.8.0-py3

# Everything below this line is common between CPU and GPU images.

# Needed for click to work
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

COPY scripts/install_deps /tmp/install_deps
RUN /tmp/install_deps && rm /tmp/install_deps

# Make Python3 default Python
RUN rm -f /usr/bin/pip && ln -s /usr/bin/pip3 /usr/bin/pip
RUN rm -f /usr/bin/python && ln -s /usr/bin/python3 /usr/bin/python

WORKDIR /opt/src/
ENV PYTHONPATH=/opt/src:/opt/tf-models:/opt/tf-models/slim:$PYTHONPATH

# Install requirements.txt
COPY ./requirements.txt /opt/src/requirements.txt
RUN pip install -r requirements.txt

COPY scripts/rastervision /usr/local/bin/
COPY ./ /opt/src/
RUN /opt/src/scripts/compile

CMD ["bash"]
