# Based on https://github.com/fchollet/keras/blob/7c6463da6f972ffaa466b0f55d06b760a98caf8e/docker/Dockerfile
FROM raster-vision-base

ARG tensorflow_version=1.0.1-cp35-cp35m

RUN pip install https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-${tensorflow_version}-linux_x86_64.whl && \
    pip install git+git://github.com/fchollet/keras.git@7c6463da6f972ffaa466b0f55d06b760a98caf8e

COPY run_experiment.sh /usr/local/bin/
ENTRYPOINT ["bash"]
