name: CI

on:
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image_type: [pytorch]
    env:
      DOCKER_BUILDKIT: 1
      IMAGE_TYPE: ${{ matrix.image_type }}
    steps:
      - uses: actions/checkout@v3

      - name: Free up disk space
        run: rm -rf /opt/hostedtoolcache

      - name: Build docker image and run tests
        run: ./scripts/cibuild
