name: Release

on:
  push:
    branches:
      - master
      - "[0-9]+" # Major version only
      - "[0-9]+.[0-9]+" # Major and minor version
      - "[0-9]+.[0-9]+.[0-9]+" # Major, minor, and patch version
    tags:
      - "*"

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image_type: [pytorch]
    env:
      DOCKER_BUILDKIT: 1
      IMAGE_TYPE: ${{ matrix.image_type }}
    steps:
      - uses: actions/checkout@v3

      - run: ./scripts/cibuild

      - run: docker system prune -f

      - run: ./scripts/test "style_tests"

      - run: ./scripts/test "unit_tests"

      - run: ./scripts/test "integration_tests"

      - run: ./scripts/test "coverage"

      - uses: codecov/codecov-action@v3

      - run: ./scripts/cipublish
        env:
          QUAY_USER: ${{ secrets.QUAY_RASTERVISION_USER }}
          QUAY_PASSWORD: ${{ secrets.QUAY_RASTERVISION_PASSWORD }}

